services:
  app:
    build:
      context: .
      target: ${TARGET:-dev}
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

networks:
  resumeai-network:
    driver: bridge
