services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

networks:
  resumeai-network:
    driver: bridge
